{
  uvodniStranka {
    data {
      attributes {
        Obrazek {
          data {
            attributes {
              url
              alternativeText
              formats
            }
          }
        }
        Slogan
        Popis
        Kontakty {
          Funkce
          vedouci {
            data {
              attributes {
                Jmeno
                Telefon
                Email
                Fotka {
                  data {
                    attributes {
                      url
                      formats
                    }
                  }
                }
              }
            }
          }
        }
        Klubovny {
          Nazev
          Adresa
          MapyCzKod
          Obrazky {
            data {
              attributes {
                url
                formats
              }
            }
          }
          spravce {
            data {
              attributes {
                Jmeno
                Telefon
                Email
              }
            }
          }
        }
        Sponzori {
          Nazev
          Odkaz
          Obrazek {
            data {
              attributes {
                url
                formats
              }
            }
          }
        }
        SocialMediaObrazek {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
  oddily {
    data {
      id
      attributes {
        Obrazek {
          data {
            attributes {
              url
              alternativeText
              formats
            }
          }
        }
        Nazev
        Url
        Typ
        druziny {
          data {
            attributes {
              Nazev
            }
          }
        }
      }
    }
  }
  stredisko {
    data {
      attributes {
        Nazev
        Email
      }
    }
  }
}
